//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Libreria.Models.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetReserva
    {
        public long IdDetReserva { get; set; }
        public long IdReserva { get; set; }
        public short IdProducto { get; set; }
        public short Cantidad { get; set; }
    
        public virtual Producto Producto { get; set; }
        public virtual Reserva Reserva { get; set; }
    }
}
