//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Libreria.Models.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolUsuario
    {
        public short IdRolUsuario { get; set; }
        public Nullable<short> IdUsuario { get; set; }
        public Nullable<short> IdRol { get; set; }
        public Nullable<short> IdSucursal { get; set; }
        public Nullable<System.DateTime> FechaREG { get; set; }
        public Nullable<bool> Activo { get; set; }
    
        public virtual Rol Rol { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
