//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Libreria.Models.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock
    {
        public int IdStock { get; set; }
        public short IdSucursal { get; set; }
        public short IdProducto { get; set; }
        public short IdProveedor { get; set; }
        public short Cantidad { get; set; }
        public decimal PrecioUnitario { get; set; }
        public decimal CostoVenta { get; set; }
        public System.DateTime FechaVencimiento { get; set; }
        public short IdUsuario { get; set; }
        public System.DateTime FechaREG { get; set; }
        public bool Activo { get; set; }
    
        public virtual Proveedor Proveedor { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Producto Producto { get; set; }
        public virtual Sucursal Sucursal { get; set; }
    }
}
