//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Libreria.Models.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.RolUsuario = new HashSet<RolUsuario>();
            this.Stock = new HashSet<Stock>();
            this.Factura = new HashSet<Factura>();
        }
    
        public short IdUsuario { get; set; }
        public Nullable<int> IdSujeto { get; set; }
        public Nullable<short> IdClasificacion { get; set; }
        public string Login { get; set; }
        public string Pwd { get; set; }
        public bool Activo { get; set; }
        public int intento { get; set; }
        public byte[] foto { get; set; }
        public Nullable<System.DateTime> fechareg { get; set; }
        public Nullable<System.DateTime> fechaultimo { get; set; }
        public byte estado { get; set; }
    
        public virtual Clasificacion Clasificacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RolUsuario> RolUsuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stock> Stock { get; set; }
        public virtual Sujeto Sujeto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Factura> Factura { get; set; }
    }
}
